# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

r_check_args: '--use-valgrind'

addons:
  apt:
    packages:
      - valgrind
      - g++-4.9 # "WARNING: Only g++ version 4.7.2 or greater can be used with RcppArmadillo."

env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
