# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cholC <- function(x) {
    .Call('GauPro_cholC', PACKAGE = 'GauPro', x)
}

solveC <- function(A, b) {
    .Call('GauPro_solveC', PACKAGE = 'GauPro', A, b)
}

corr_gauss_matrixC <- function(x, y, theta) {
    .Call('GauPro_corr_gauss_matrixC', PACKAGE = 'GauPro', x, y, theta)
}

#' @export
corr_gauss_matrix_symC <- function(x, theta) {
    .Call('GauPro_corr_gauss_matrix_symC', PACKAGE = 'GauPro', x, theta)
}

#' @export
corr_gauss_matrix_sym_armaC <- function(x, theta) {
    .Call('GauPro_corr_gauss_matrix_sym_armaC', PACKAGE = 'GauPro', x, theta)
}

deviance_part <- function(theta, nug, X, Z, Kinv) {
    .Call('GauPro_deviance_part', PACKAGE = 'GauPro', theta, nug, X, Z, Kinv)
}

devianceC <- function(theta, nug, X, Z, K) {
    .Call('GauPro_devianceC', PACKAGE = 'GauPro', theta, nug, X, Z, K)
}

deviance_fngr_theta <- function(X, Z, K) {
    .Call('GauPro_deviance_fngr_theta', PACKAGE = 'GauPro', X, Z, K)
}

deviance_fngr_nug <- function(X, Z, K) {
    .Call('GauPro_deviance_fngr_nug', PACKAGE = 'GauPro', X, Z, K)
}

deviance_fngr_joint <- function(X, Z, K) {
    .Call('GauPro_deviance_fngr_joint', PACKAGE = 'GauPro', X, Z, K)
}

deviance_grad_theta <- function(X, K, Kinv, y) {
    .Call('GauPro_deviance_grad_theta', PACKAGE = 'GauPro', X, K, Kinv, y)
}

deviance_grad_nug <- function(X, K, Kinv, y) {
    .Call('GauPro_deviance_grad_nug', PACKAGE = 'GauPro', X, K, Kinv, y)
}

deviance_grad_joint <- function(X, K, Kinv, y) {
    .Call('GauPro_deviance_grad_joint', PACKAGE = 'GauPro', X, K, Kinv, y)
}

Gaussian_deviance_part <- function(theta, nug, X, Z, Kinv) {
    .Call('GauPro_Gaussian_deviance_part', PACKAGE = 'GauPro', theta, nug, X, Z, Kinv)
}

#' @export
Gaussian_devianceC <- function(theta, nug, X, Z) {
    .Call('GauPro_Gaussian_devianceC', PACKAGE = 'GauPro', theta, nug, X, Z)
}

#' Gaussian hessian in C
#'
#' @param XX point to find Hessian at
#' @param X matrix of data points
#' @param Z matrix of output
#' @param Kinv inverse of correlation matrix
#' @param mu_hat mean estimate
#' @param theta correlation parameters
#'
#' @return Hessian matrix
#' @export
Gaussian_hessianCC <- function(XX, X, Z, Kinv, mu_hat, theta) {
    .Call('GauPro_Gaussian_hessianCC', PACKAGE = 'GauPro', XX, X, Z, Kinv, mu_hat, theta)
}

rcpp_hello_world <- function() {
    .Call('GauPro_rcpp_hello_world', PACKAGE = 'GauPro')
}

pred_meanC <- function(XX, kx_xx, mu_hat, Kinv, Z) {
    .Call('GauPro_pred_meanC', PACKAGE = 'GauPro', XX, kx_xx, mu_hat, Kinv, Z)
}

pred_var <- function(XX, kxx, kx_xx, s2_hat, Kinv, Z) {
    .Call('GauPro_pred_var', PACKAGE = 'GauPro', XX, kxx, kx_xx, s2_hat, Kinv, Z)
}

pred_cov <- function(XX, kxx, kx_xx, s2_hat, Kinv, Z) {
    .Call('GauPro_pred_cov', PACKAGE = 'GauPro', XX, kxx, kx_xx, s2_hat, Kinv, Z)
}

